using UnityEngine;

public class ManagerIK : MonoBehaviour
{

    Animator animator;
    public bool ikActive = false;
    public Transform objTarget;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        animator = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {

    }

    public void OnAnimatorIK()
    {
        if (animator)
        {
            if (ikActive)
            {
                if (objTarget != null)
                {
                    animator.SetLookAtWeight(1);
                    animator.SetLookAtPosition(objTarget.position);
                }
                else
                {
                    animator.SetLookAtWeight(0);
                }
            }
        }

    }
}
